# action.yml
name: 'GitHub Action to push subdirectories to separate repositories.'
description: 'GitHub Action to push subdirectories to separate repositories.'
author: 'Daniel Kim <daniel@bitproject.org>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'purple'