# action.yml
name: 'GitHub Action to Push a Subdirectory to Another Repo'
description: 'Automatically push a single subdirectory to a separate repo'
author: 'Axel <axel@fantasy-calendar.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'purple'
